### ISSUE TITLE
npm issue, sorry idk how to add a label :(

### ISSUE THREAD

**Issue by Skkirmish** [Deivu/Kongou#4]
When i try to install npm erlpack i get this error message, any idea what could fix this problem?

 node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! erlpack@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the erlpack@0.1.3 install script.

**Comment by Deivu** [comment]
just omit Erlpack from installing, I think Erlpack need some other node things if I remember, the build tools thingy(?)

**Comment by kakarot-dev** [comment]
Is erlpack even being used?
